# This workflow loosely replicates the logic in .woodpecker.yml
name: Run tests
on:
  push:
    branches:
      - lw-*

env:
  CI_RUST_VERSION: "1.78"
  CARGO_HOME: .cargo_home

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
          show-progress: "false"

      - name: Get date for cache key
        id: get-date
        run: |
          echo "date=$(/bin/date -u "+%Y%m%d")" >> $GITHUB_OUTPUT

      - name: Cargo home cache
        uses: actions/cache@v4
        with:
          path: ${{ env.CARGO_HOME }}
          key: rust-cargo-home-${{ env.CI_RUST_VERSION }}-${{ hashFiles('**/Cargo.toml', '**/Cargo.lock') }}
          restore-keys: |
            rust-cargo-home-${{ env.CI_RUST_VERSION }}-
            rust-cargo-home-

      # https://github.com/rust-lang/rustup/issues/2886
      - name: Disable rustup self update
        run: rustup set auto-self-update disable

      - name: Set Rust version to ${{ env.CI_RUST_VERSION }}
        run: rustup default "$CI_RUST_VERSION"

      - name: Install Rust nightly toolchain
        run: rustup toolchain install nightly

      - name: Cargo fmt
        run: |
          rustup component add --toolchain nightly rustfmt
          cargo +nightly fmt -- --check

      - name: Cargo check
        run: cargo check --all-features --all-targets

      - name: Cargo clippy
        run: |
          rustup component add clippy
          cargo clippy --all-targets --all-features

      - name: Cargo test
        run: cargo test --workspace --no-fail-fast

      - name: Cargo doc
        run: cargo doc --all-features

      - name: Cargo run actix example
        run: cargo run --example local_federation actix-web

      - name: Cargo run axum example
        run: cargo run --example local_federation axum
